sudo: false
language: python
cache: pip
python:
  - '2.7'
install:
  - pip install tox-travis
before_script:
  - 'cp instance/application.example.cfg instance/application.cfg'
  - 'cp tests/resources/crypto_files/disposable.private.pem instance/private_key.pem'
  - 'cp tests/resources/crypto_files/disposable.public.pem instance/public_cert.pem'
script: tox
